# 必须是字符串
version: '3.8'

services: 
    cwy516project: 
        image: cwy516project:v1
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "5100:80"
    consul1: 
        image: consul:latest
        container_name: consul1
        restart: always
        ports: 
            - "8500:8500"
            - "53"
        hostname: "consul-server1"
        command: agent -server -ui -bootstrap-expect=3 -node=consul-server1 -disable-host-node-id -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1
        volumes: 
            - /usr/consul/consul1:/consul/data
    consul2: 
        image: consul:latest
        container_name: consul2
        restart: always
        ports: 
            - "8501:8500"
            - "53"
        hostname: "consul-server2"
        command: agent -server -ui -bootstrap-expect=3 -node=consul-server2 -disable-host-node-id -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1 -retry-join=192.168.123.233:8300
        volumes: 
            - /usr/consul/consul2:/consul/data
    consul3: 
        image: consul:latest
        container_name: consul3
        restart: always
        ports: 
            - "8502:8500"
            - "53"
        hostname: "consul-server3"
        command: agent -server -ui -bootstrap-expect=3 -node=consul-server3 -disable-host-node-id -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1 -retry-join=consul-server1
        volumes: 
            - /usr/consul/consul3:/consul/data
    consul4: 
        image: consul:latest
        container_name: consul4
        restart: always
        ports: 
            - "8503:8500"
            - "53"
        hostname: "consul-client"
        command: agent -ui -node=consul-client -client=0.0.0.0 -bind=0.0.0.0 -disable-host-node-id -datacenter=dc1 -retry-join=consul-server1
        volumes: 
            - /usr/consul/consul4:/consul/data


